# Generated by Django 3.2.2 on 2021-05-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0005_chat_unread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='unread',
        ),
    ]
