# Generated by Django 3.2.2 on 2021-05-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0006_remove_chat_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hash',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
